# config file for ros2 joy_teleop node
joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: diff_drive_controller/cmd_vel
      deadman_buttons: [5]
      axis_mappings:
        twist-linear-x:
          axis: 1
          scale: 0.6
          offset: 0.0
        twist-angular-z:
          axis: 0
          scale: 4.0
          offset: 0.0

    camera_tilt_horizontal:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: /camera_position_controller/cmd_vel
      deadman_buttons: [4]
      axis_mappings:
        twist-angular-z:
          axis: 3
          scale: 1.0
          offset: 0.0

